networks:
  fabric-network:

services:
  # CA for Org1
  ca.org1.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    ports:
      - "7054:7054"
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.example.com
    networks:
      - fabric-network

  # CA for Org2
  ca.org2.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
    ports:
      - "8054:7054"
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org2.example.com
    networks:
      - fabric-network

  # Peer0 for Org1
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CONFIG=/etc/hyperledger/fabric/core.yaml
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERTFILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEYFILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_SNAPSHOTS_ROOTDIR=/etc/hyperledger/fabric/snapshots
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
    ports:
      - "7051:7051"
    volumes:
      - /home/sumanth/fabric-code/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - /home/sumanth/fabric-code/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
      - ./config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - /home/sumanth/fabric-code/snapshots:/etc/hyperledger/fabric/snapshots
    networks:
      - fabric-network

  # Peer1 for Org1
  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer1.org1.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CONFIG=/etc/hyperledger/fabric/core.yaml
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERTFILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEYFILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_SNAPSHOTS_ROOTDIR=/var/hyperledger/fabric/snapshots
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:8051
    ports:
      - "8051:8051"
    volumes:
      - /home/sumanth/fabric-code/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - /home/sumanth/fabric-code/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/tls
      - ./config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - /home/sumanth/fabric-code/snapshots:/var/hyperledger/fabric/snapshots
    networks:
      - fabric-network

  # Orderer1
  orderer1.example.com:
    container_name: orderer1.example.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/fabric/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrgMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/msp
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_TLS_ENABLED=true
      - ORDERER_TLS_CERTFILE=/etc/hyperledger/fabric/tls/server.crt
      - ORDERER_TLS_KEYFILE=/etc/hyperledger/fabric/tls/server.key
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/fabric/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_CLUSTER_LISTENPORT=7050
      - ORDERER_GENERAL_CLUSTER_SERVERCERTIFICATE=/etc/hyperledger/fabric/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_SERVERPRIVATEKEY=/etc/hyperledger/fabric/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/fabric/tls/ca.crt]
    ports:
      - "7050:7050"
    volumes:
      - /home/sumanth/fabric-code/configtx:/etc/hyperledger/fabric/configtx
      - /home/sumanth/fabric-code/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp:/etc/hyperledger/fabric/msp
      - /home/sumanth/fabric-code/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls:/etc/hyperledger/fabric/tls
      - ./config/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
    networks:
      - fabric-network

  # Orderer2
  orderer2.example.com:
    container_name: orderer2.example.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/fabric/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrgMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/fabric/msp
      - ORDERER_TLS_ENABLED=true
      - ORDERER_TLS_CERTFILE=/etc/hyperledger/fabric/tls/server.crt
      - ORDERER_TLS_KEYFILE=/etc/hyperledger/fabric/tls/server.key
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/fabric/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_CLUSTER_LISTENPORT=8050
      - ORDERER_GENERAL_CLUSTER_SERVERCERTIFICATE=/etc/hyperledger/fabric/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_SERVERPRIVATEKEY=/etc/hyperledger/fabric/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/fabric/tls/ca.crt]
    ports:
      - "8050:7050"
    volumes:
      - /home/sumanth/fabric-code/configtx:/etc/hyperledger/fabric/configtx
      - /home/sumanth/fabric-code/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp:/etc/hyperledger/fabric/msp
      - /home/sumanth/fabric-code/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls:/etc/hyperledger/fabric/tls
      - ./config/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
    networks:
      - fabric-network
